### PR TITLE
Node operator guide

### PR DESCRIPTION
**Pull request by guanzo**
#82

Adds documentation for

* Creating a FIL wallet. Do these choices look okay?
* How to monitor nodes
* How to receive payments

### CODE REVIEW

**Review by DiegoRBaquero — APPROVED** [review]
Are there not better, more frequently updated, guides for the FIL wallet section that are out there in the ecosystem?

**Comment by guanzo** [comment]
The official docs https://docs.filecoin.io/get-started/overview/#wallets
Should we link to that?

**Comment by DiegoRBaquero** [comment]
> The official docs https://docs.filecoin.io/get-started/overview/#wallets Should we link to that?

That works, we don't want to burden ourselves with that section

**Comment by gruns** [comment]
> That works, we don't want to burden ourselves with that section

agreed. we definitely do *not* want to have instructions on how/where to set up a filecoin wallet in our docs. nor do we want to maintain this. we should link elsewhere

that said, the official docs at https://docs.filecoin.io/get-started/overview/#wallets are bad. theyre about wallet implementations

1. i think most node ops who dont already have a fil wallet will want to use a hosted wallet, like coinbase or binance
2. the linked instructions dont even mention such hosted wallet
3. like how many node ops will want to set up and run lotus just to get a fil wallet? my guess: zero

@guanzo lets
1. look for guides on how to get a wallet, including hosted wallets
2. if we cant find any, who should we speak with at PL to write such docs? bc this would be useful for many outside of saturn, too

**Pull request merged**
