### PR TITLE
Run Lassie publicly

### PR DESCRIPTION
**Pull request by joaosa**
Run on 0.0.0.0, so we can scrape metrics.

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
Operators are not required to have the port open. Just a note.

**Comment by hannahhoward** [comment]
@DiegoRBaquero I think metric scraping is just trusted nodes anyway no?

**Comment by hannahhoward** [comment]
Also though, I wonder if we should throw the metrics only on a separate port to avoid exposing the whole api?

**Comment by DiegoRBaquero** [comment]
> @DiegoRBaquero I think metric scraping is just trusted nodes anyway no?

Ah ok, that should be fine then

**Comment by DiegoRBaquero** [comment]
> Also though, I wonder if we should throw the metrics only on a separate port to avoid exposing the whole api?

This would allow anyone to (ab)use L1s' lassie to fetch content or DDoS them. I agree we should only expose metrics

**Comment by joaosa** [comment]
> > Also though, I wonder if we should throw the metrics only on a separate port to avoid exposing the whole api?
> 
> This would allow anyone to (ab)use L1s' lassie to fetch content or DDoS them. I agree we should only expose metrics

That is a good point. We should only expose metrics if possible.

**Comment by joaosa** [comment]
Closing this, as we don't need it anymore

**Pull request closed without merging**
